server:
  port: 9090

keycloak:
  realm: demoservice
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: democlient
  credentials:
    secret: 0v39dkNOY2PjWRxdcOuf7QNQ7FeZ1wiE
  use-resource-role-mappings: true
  bearer-only: true